#!/bin/bash
# Railway Setup Script
# This script helps you configure your Discord bot on Railway

echo "🤖 Avengers Bot - Railway Setup"
echo "================================"
echo ""
echo "This script will help you set environment variables on Railway."
echo ""
echo "REQUIREMENTS:"
echo "1. Railway CLI installed: https://docs.railway.app/develop/cli"
echo "2. Logged in: run 'railway login' first"
echo "3. Your Discord bot token ready"
echo ""
echo "STEPS:"
echo "1. Get your Discord bot token from: https://discord.com/developers/applications"
echo "2. Copy the token"
echo "3. Run these commands:"
echo ""
echo "   railway login"
echo "   railway link"
echo "   railway variables set TOKEN=your_token_here"
echo "   railway up"
echo ""
echo "Or set via Railway Dashboard:"
echo "1. Go to https://railway.app/project/[your-project-id]"
echo "2. Click 'av-bot' service"
echo "3. Click 'Variables' tab"
echo "4. Add: TOKEN = [your_token_here]"
echo "5. Redeploy"
echo ""
